package eu.kanade.tachiyomi.extension.es.manhwashot

import eu.kanade.tachiyomi.source.model.Filter

open class UriPartFilter(displayName: String, private val vals: Array<Pair<String, String>>) :
    Filter.Select<String>(displayName, vals.map { it.first }.toTypedArray()) {
    fun toUriPart() = vals[state].second
}

// Secciones de la web: /explorar/adult/, /explorar/bl/, /explorar/shoujo/, /explorar/manga/
class SectionFilter :
    UriPartFilter(
        "Sección",
        arrayOf(
            "Todos" to "",
            "+18" to "adult",
            "BL" to "bl",
            "Shoujo" to "shoujo",
            "Manga" to "manga",
        ),
    )

// Géneros de la web: /explorar/?genero=<slug> (mismo orden que usa el sitio)
class GenreFilter :
    UriPartFilter(
        "Género",
        arrayOf("Todos" to "") + GENRES,
    )

private val GENRES: Array<Pair<String, String>> = arrayOf(
    "Romance" to "romance",
    "Drama" to "drama",
    "+18" to "18",
    "Fantasía" to "fantasia",
    "Comedia" to "comedia",
    "Acción" to "accion",
    "Aventura" to "aventura",
    "Boys Love" to "boys-love",
    "Adulto" to "adulto",
    "Ecchi" to "ecchi",
    "Harem" to "harem",
    "Josei" to "josei",
    "Recuentos de la vida" to "recuentos-de-la-vida",
    "Shoujo" to "shoujo",
    "Magia" to "magia",
    "Reencarnación" to "reencarnacion",
    "Vida Escolar" to "vida-escolar",
    "Artes Marciales" to "artes-marciales",
    "Smut" to "smut",
    "BL" to "bl",
    "Psicológico" to "psicologico",
    "Maduro" to "maduro",
    "Yaoi" to "yaoi",
    "Misterio" to "misterio",
    "Tragedia" to "tragedia",
    "Familia" to "familia",
    "Sobrenatural" to "sobrenatural",
    "Sistema" to "sistema",
    "Shounen" to "shounen",
    "Demonios" to "demonios",
    "Histórico" to "historico",
    "Manhwa +19" to "manhwa-19",
    "Ciencia Ficción" to "ciencia-ficcion",
    "Regresión" to "regresion",
    "Supernatural" to "supernatural",
    "MangoScan" to "mangoscan",
    "Supervivencia" to "supervivencia",
    "Manhwa" to "manhwa",
    "+15" to "15",
    "Seinen" to "seinen",
    "Shonen" to "shonen",
    "Venganza" to "venganza",
    "Action" to "action",
    "Transmigración" to "transmigracion",
    "Milf" to "milf",
    "Superpoderes" to "superpoderes",
    "Mujer casada" to "mujer-casada",
    "Fantasy" to "fantasy",
    "Omegaverse" to "omegaverse",
    "Primer amor" to "primer-amor",
    "Mucho Gogogo" to "mucho-gogogo",
    "Horror" to "horror",
    "Aliado" to "aliado",
    "NTR" to "ntr",
    "Manhua" to "manhua",
    "boyslove" to "boyslove",
    "Historia" to "historia",
    "Recomendado" to "recomendado",
    "Apocalíptico" to "apocaliptico",
    "Isekai" to "isekai",
    "Comedy" to "comedy",
    "moderno" to "moderno",
    "Mujer mayor" to "mujer-mayor",
    "Relacion secreta" to "relacion-secreta",
    "+19" to "19",
    "Harén" to "haren",
    "Adventure" to "adventure",
    "Sin censura" to "sin-censura",
    "ESCOLAR" to "escolar",
    "Murim" to "murim",
    "Toxicidad" to "toxicidad",
    "Crimen" to "crimen",
    "BL Sin Censura" to "bl-sin-censura",
    "Retornado" to "retornado",
    "Girls Love" to "girls-love",
    "Historia corta" to "historia-corta",
    "Amigos de la infancia" to "amigos-de-la-infancia",
    "Deporte" to "deporte",
    "Harem Inverso" to "harem-inverso",
    "Universidad" to "universidad",
    "Gore" to "gore",
    "Nuevo" to "nuevo",
    "Bestias" to "bestias",
    "Militar" to "militar",
    "Anti-Héroe" to "anti-heroe",
    "Thriller" to "thriller",
    "Slice of Life" to "slice-of-life",
    "Academia" to "academia",
    "Fetiches" to "fetiches",
    "Bara bl Scan" to "bara-bl-scan",
    "Madrastra" to "madrastra",
    "Manwha" to "manwha",
    "Madre e hija" to "madre-e-hija",
    "Eternal Scan" to "eternal-scan",
    "Dominación" to "dominacion",
    "CelestialMoon Scan" to "celestialmoon-scan",
    "Historias cortas" to "historias-cortas",
    "+ 18 Sin Censura" to "18-sin-censura",
    "Oficina" to "oficina",
    "Yuri" to "yuri",
    "Mujer madura" to "mujer-madura",
    "Meian" to "meian",
    "Recuerdo de la vida" to "recuerdo-de-la-vida",
    "Sistema de Niveles" to "sistema-de-niveles",
    "Rape" to "rape",
    "Pareja casada" to "pareja-casada",
    "#BDSM" to "bdsm",
    "Cultivación" to "cultivacion",
    "Guerra" to "guerra",
    "Odio-Amor" to "odio-amor",
    "LunariaScan" to "lunariascan",
    "Manga" to "manga",
    "Hermes" to "hermes",
    "Universitario" to "universitario",
    "mafia" to "mafia",
    "Deportes" to "deportes",
    "amor no correspondido" to "amor-no-correspondido",
    "Corrupción" to "corrupcion",
    "Mystery" to "mystery",
    "Musica" to "musica",
    "Webtoon" to "webtoon",
    "Martial Arts" to "martial-arts",
    "Realidad" to "realidad",
    "Infidelidad" to "infidelidad",
    "Intercambio de parejas" to "intercambio-de-parejas",
    "Realidad Virtual" to "realidad-virtual",
    "Amigos con derechos" to "amigos-con-derechos",
    "boys" to "boys",
    "Postapocalíptico" to "postapocaliptico",
    "PununiScan" to "pununiscan",
    "Bebes" to "bebes",
    "furro" to "furro",
    "triángulo amoroso" to "triangulo-amoroso",
    "Pechos Grandes" to "pechos-grandes",
    "Puto-Amo" to "puto-amo",
    "Monstruos" to "monstruos",
    "Actor" to "actor",
    "Mecha" to "mecha",
    "Fantansía" to "fantansia",
    "Historical" to "historical",
    "Parodia" to "parodia",
    "Policiaco" to "policiaco",
    "Peleas" to "peleas",
    "Juego" to "juego",
    "GL" to "gl",
    "Morocho hermoso" to "morocho-hermoso",
    "Español" to "espanol",
    "Epoca" to "epoca",
    "YaoiphiliaScan" to "yaoiphiliascan",
    "Psychological" to "psychological",
    "Garganta Profunda" to "garganta-profunda",
    "Tragedy" to "tragedy",
    "Evolución" to "evolucion",
    "Vampiros" to "vampiros",
    "Tetón" to "teton",
    "Convivencia" to "convivencia",
    "DiferenciaDeEstatus" to "diferenciadeestatus",
    "Maduras" to "maduras",
    "Medieval" to "medieval",
    "mucho gogo" to "mucho-gogo",
    "Pareja Sexual" to "pareja-sexual",
    "Pantallas de sistemas" to "pantallas-de-sistemas",
    "3D" to "3d",
    "Relación por convivencia" to "relacion-por-convivencia",
    "Villana" to "villana",
    "Incesto" to "incesto",
    "caliente" to "caliente",
    "Toxicidad nivel Chernóbil" to "toxicidad-nivel-chernobil",
    "MILFs" to "milfs",
    "Cohabitación" to "cohabitacion",
    "Netori" to "netori",
    "gogo" to "gogo",
    "toxico" to "toxico",
    "Manipulación" to "manipulacion",
    "guideverse" to "guideverse",
    "AV" to "av",
    "Seducida" to "seducida",
    "Lencería" to "lenceria",
    "ScanStarts" to "scanstarts",
    "Creampie" to "creampie",
    "Mujer Traviesa" to "mujer-traviesa",
    "Antologia" to "antologia",
    "# Tetonas" to "tetonas",
    "Cultivo" to "cultivo",
    "Campus" to "campus",
    "Posible Harem" to "posible-harem",
    "Crime" to "crime",
    "Suspenso" to "suspenso",
    "shojo" to "shojo",
    "Habilidades" to "habilidades",
    "Exclusivo" to "exclusivo",
    "Telenovela" to "telenovela",
    "Enemies to lovers" to "enemies-to-lovers",
    "Sports" to "sports",
    "mamada" to "mamada",
    "Contenido sexual" to "contenido-sexual",
    "Cazadora de Mangas" to "cazadora-de-mangas",
    "Masoquismo" to "masoquismo",
    "Tentáculos" to "tentaculos",
    "Terror" to "terror",
    "Niños" to "ninos",
    "PrincipeCaiusFanSub" to "principecaiusfansub",
    "basado en novela" to "basado-en-novela",
    "Enemigos" to "enemigos",
    "corto" to "corto",
    "Adolescente" to "adolescente",
    "villano" to "villano",
    "Rubias" to "rubias",
    "Grandes Tetas" to "grandes-tetas",
    "Hetero" to "hetero",
    "Vip" to "vip",
    "Protagonista OP" to "protagonista-op",
    "Comic" to "comic",
    "Urbano" to "urbano",
    "Rubio" to "rubio",
    "romance de oficina" to "romance-de-oficina",
    "embarazo" to "embarazo",
    "Trasero Grande" to "trasero-grande",
    "gran culo" to "gran-culo",
    "Diferencia de edad" to "diferencia-de-edad",
    "Zombis" to "zombis",
    "Stream" to "stream",
    "A Todo Color" to "a-todo-color",
    "Che tenete un poco de amor propio" to "che-tenete-un-poco-de-amor-propio",
    "Tetas grandes" to "tetas-grandes",
    "Xianxia" to "xianxia",
    "Younger Seme" to "younger-seme",
    "Orgia" to "orgia",
    "analisis" to "analisis",
    "Ajumma" to "ajumma",
    "Tetas Enormes" to "tetas-enormes",
    "MC" to "mc",
    "humillacion" to "humillacion",
    "Ángeles" to "angeles",
    "hot" to "hot",
    "Universitarios" to "universitarios",
    "Gender Bender" to "gender-bender",
    "Romance? Quien sabe" to "romance-quien-sabe",
    "Chica alta" to "chica-alta",
    "posesion" to "posesion",
    "SnowBunnyScan" to "snowbunnyscan",
    "vampiro" to "vampiro",
    "bebé" to "bebe",
    "Género Bender" to "genero-bender",
    "Novela" to "novela",
    "Cola De Caballo" to "cola-de-caballo",
    "ManhwaShot" to "manhwashot",
    "Muchas Waifus" to "muchas-waifus",
    "Fantasmas" to "fantasmas",
    "Wuxia" to "wuxia",
    "Combate" to "combate",
    "Apocalipsis" to "apocalipsis",
    "constelaciones" to "constelaciones",
    "Cornudo" to "cornudo",
    "Grandes pollas" to "grandes-pollas",
    "Infiel" to "infiel",
    "mamá" to "mama",
    "Mature3DComics" to "mature3dcomics",
    "Traición" to "traicion",
    "Nigromante" to "nigromante",
    "Erótico" to "erotico",
    "Cómics 3D" to "comics-3d",
    "ambiente europeo" to "ambiente-europeo",
    "paranormal" to "paranormal",
    "confinamiento" to "confinamiento",
    "amigos" to "amigos",
    "RelaciónPorContrato" to "relacionporcontrato",
    "Rey y Subdito" to "rey-y-subdito",
    "Creador de ciudades" to "creador-de-ciudades",
    "Domador de bestias" to "domador-de-bestias",
    "Escuela" to "escuela",
    "Risemara" to "risemara",
    "Dragones" to "dragones",
    "Dominación y Sumisión" to "dominacion-y-sumision",
    "Problemas Familiares" to "problemas-familiares",
    "Prota OP" to "prota-op",
    "Chicas Monstruo" to "chicas-monstruo",
    "Novio Sádico" to "novio-sadico",
    "Comida" to "comida",
    "extraterrestre" to "extraterrestre",
    "Prota Badas" to "prota-badas",
    "Chupar Tetas" to "chupar-tetas",
    "Transmigración entre mundos" to "transmigracion-entre-mundos",
    "Casadas" to "casadas",
    "Madura" to "madura",
    "Ahegao" to "ahegao",
    "Sci-fi" to "sci-fi",
    "Netorare" to "netorare",
    "Original" to "original",
    "Daval3D" to "daval3d",
    "Philosophical" to "philosophical",
    "Esclavas" to "esclavas",
    "Cazador" to "cazador",
    "GangBang" to "gangbang",
    "#Fetiche" to "fetiche",
    "Gafas" to "gafas",
)
